# Generated by Django 5.0 on 2023-12-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0002_location_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("build_name", models.CharField(max_length=100)),
                (
                    "build_img",
                    models.ImageField(
                        upload_to="building_images/", verbose_name="Building Image"
                    ),
                ),
                ("build_description", models.TextField()),
            ],
        ),
    ]
