# Generated by Django 4.2.5 on 2023-12-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_location_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location_name', models.CharField(max_length=100)),
                ('from_location_lat', models.FloatField()),
                ('from_location_lng', models.FloatField()),
                ('to_location_name', models.CharField(max_length=100)),
                ('to_location_lat', models.FloatField()),
                ('to_location_lng', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
