# Generated by Django 5.0 on 2023-12-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_location_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=100)),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('event_name', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('event_image', models.ImageField(upload_to='event_images/')),
                ('event_timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
