# Generated by Django 5.0 on 2023-12-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0003_building"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("comment", models.TextField()),
                ("admin_comment", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
