# Generated by Django 4.2.5 on 2023-12-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_searchlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlocation',
            name='travel_mode',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
