# Generated by Django 4.2.5 on 2023-12-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_searchlocation_travel_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlocation',
            name='travel_mode',
            field=models.CharField(choices=[('WALKING', 'Walking'), ('DRIVING', 'Driving'), ('CYCLING', 'Cycling')], max_length=10),
        ),
    ]
