# Generated by Django 4.2.5 on 2023-12-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_alter_searchlocation_travel_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlocation',
            name='search_by',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
