# Generated by Django 4.2.5 on 2023-12-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_campusevent'),
        ('navigation', '0004_feedback'),
        ('navigation', '0006_searchlocation_search_by'),
    ]

    operations = [
    ]
