# Generated by Django 4.2.5 on 2023-12-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0007_merge_20231205_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusevent',
            name='event_id',
        ),
    ]
