# Generated by Django 4.2.5 on 2023-12-06 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('navigation', '0009_customuser_usersession_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlocation',
            name='search_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
