# Generated by Django 4.2.5 on 2023-12-06 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('navigation', '0011_alter_searchlocation_search_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlocation',
            name='search_by',
            field=models.ForeignKey(blank=True, default='NULL', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
